# Abstract
In the following report, we used text mining techniques to predict company ratings through Glassdoor Reviews. </p>

Firstly, we separated the positive reviews from the negatives one, then as part of our pre-treatment we applied different techniques, such as removal of stopwords and lemmatization and performed an exploratory analysis. </p>

Secondly, based on an unsupervised analysis, we observed through the application of the Latent Dirichlet Allocation (LDA) method that, first, it was difficult to distinguish which words are more specific to each topic because the topics had a lot of common words and second,that no company is closer to a topic than another. This enable us to assert that LDA is irrelevant in this case.</p>

Finally, we concluded our work with supervised learning methods in order to find the best methods relatively to the number of pros and cons revieews to predict the rating. After comparison, we concluded that the best model was the one with the lowest RMSE, whihc was given by a random forest using TF-IDF+LSA with 30 topics for the pros and 20 for the cons.
</p>

