# Introduction

As part of a [Text Mining](https://hecnet.unil.ch/hec/syllabus/descriptif/2441) course taught at HEC Lausanne by Professor [Marc-Olivier Boldi](https://hecnet.unil.ch/hec/recherche/fiche?pnom=mboldi&dyn_lang=en), our team has decided to conduct a project to determine the rating of five banks ( **JP Morgan **,  **Deutsche Bank **,  **TD **,  **HSBC Holdings ** and  **UBS **) based on reviews from the [Glassdoor](http://glassdoor.com/)'s website. </p>

Glassdoor is a website where current and former company employees anonymously evaluate their salary, work environment and the company. Being the reference for obtaining information that is not made public by companies, the website has a large audience which is mainly due to the fact that the current and former employees are very active on the platform and therefore counts a lot of reviews on different companies. </p>

The aim of our project is to be able to predict company rating of the five following banks: JP Morgan, Deutsche Bank, TD, HSBC Holdings and UBS . We want to see if there are differences and similarities between the five banks in order to determine if some factors are more responsible of the success of one of the company. Are there some patterns that human resources will be able to use to increase competitiveness? Are there specific characteristics that are recurrent in the industry ? </p>

In order to achieve our objective, we will apply different techniques to extract valuable information from the texts. After performing an *exploratory analysis*, we will perform a *semantic analysis*. Then we will fit a topic model, using the Latent  *Dirichlet Allocation (LDA)* method. Finally, we will use a machine learning methods with a supervised analysis to predict which model is the best at predicting the rating. </p>


ilia: I would make the research questions into bullet points. Furthermore, regarding the last paragraph, I would say that what we're trying to do is a *regression task*. I have modified some stuff in the text in the introduction (for instance the first paragraph). In paragraph 3 we repeat ourselves on the bank. I would also add another paragraph to talk about our motivation and how knowing about how Glassdoor reviews work can give us insights into the job market or something like that to make it sound more personal to us.