---
title: "EDA-Romain"
output: html_document
---

```{r setup, include=FALSE,message=FALSE}
source(here::here("scripts/setup.R"))
```

# Exploratory Data Analysis

## Complete pros reviews set (each review is a doc)


```{r }
### Preprocessing of corpus
reviews.complete <- read.csv("/Users/romaindonati/Desktop/Text-Mining-Project-2020/data/Bank_reviews_processed.csv",stringsAsFactors = FALSE)


reviews.corpus.pro <- corpus(x = reviews.complete,
                             text_field = c("employer_pros"))

```

```{r }
### tokenization
library(lavaan)

#Romain: no need for word1 argument, as we are not concerned by symbols or whatever.
reviews.tokens.pro <- tokens(reviews.corpus.pro, 
                        remove_punct = TRUE, 
                        remove_symbols = TRUE, 
                        what="word")

#Use of stemming / could also use lemmitization
reviews.tokens.pro <- tokens_tolower(reviews.tokens.pro) %>% 
  tokens_wordstem() %>%
  tokens_remove(stopwords("english"))
```


```{r }
### Document frequency matrix
reviews.pro.dfm <- dfm(reviews.tokens.pro)

#tf_IDF
reviews.pro.dfm.tfidf<-dfm_tfidf(reviews.pro.dfm)
```

### first insights
```{r}
#sparcity dfm
sum(reviews.pro.dfm ==0)/length(reviews.pro.dfm)
sparsity(reviews.pro.dfm)

#frequency per terms 
reviews.pro.freq <- textstat_frequency(reviews.pro.dfm)
head(reviews.pro.freq, 10)

reviews.pro.freq %>%
  arrange(desc(frequency)) %>%
  filter(rank<15) %>% 
  ggplot(aes(x=feature, y=frequency)) + 
  geom_col() + 
  coord_flip() +
  labs(title="Top 15 token frequency")


#Average number of sentence in each review
mean(nsentence(reviews.corpus.pro))
```

### Cloud of words
```{r}

library(wordcloud)
wordcloud(words=reviews.pro.freq$feature,
          freq=reviews.pro.freq$docfreq,
          max.words = 100) 

```

## By Bank

```{r}
reviews.company <-reviews.complete$company
reviews.pro.dfm$company <-reviews.company
reviews.bank.pro.dfm<-dfm_group(reviews.pro.dfm,groups = "company")

#frequency per terms
reviews.bank.pro.freq <- textstat_frequency(reviews.bank.pro.dfm,groups = "company")

#tf_idf
reviews.bank.pro.dfm.tfidf<-dfm_tfidf(reviews.bank.pro.dfm)

index <- reviews.bank.pro.freq %>% top_n(15)
index <- index %>% filter(rank<15)
reviews.bank.pro.freq %>% 
  filter(feature %in% index$feature) %>% 
  ggplot(aes(feature, frequency)) + 
  geom_col() + 
  coord_flip() +
  facet_wrap(~group, ncol = 3) +
  labs(title="Whole dataset top 15 token frequency by bank")
```

### Keyness analysis for each bank compared to the other
```{r}
company <- docnames(reviews.bank.pro.dfm)
res <- numeric(length = length(company))

for (i in 1:length(company)) {
  text2.kn <- textstat_keyness(reviews.bank.pro.dfm, target = i)
  print(textplot_keyness(text2.kn))
}
```


### Compare the reviews in terms of lexical diversity
```{r}
textstat_lexdiv(reviews.bank.pro.dfm,
                measure = "I") %>%
  ggplot(aes(x = reorder(document, I), y = I)) +
  geom_point() +
  coord_flip() +
  xlab("Text") +
  ylab("Yule's index")
```

### Analysis of the differents types of score
```{r}
reviews.complete %>%
  group_by(company) %>%
  summarise(
    employer_rating = mean(employer_rating),
    work_life_balance = mean(work_life_balance, na.rm = TRUE),
    culture_values = mean(culture_values, na.rm = TRUE),
    career_opportunities = mean(career_opportunities, na.rm = TRUE),
    compensation_and_benefits = mean(compensation_and_benefits, na.rm = TRUE),
    senior_management = mean(senior_management, na.rm = TRUE),
    overall_score = mean(
      employer_rating,
      work_life_balance,
      culture_values,
      career_opportunities,
      compensation_and_benefits,
      senior_management
    )
  ) %>% kable_maker()
```

### Job analysis
Here my goal is to see if jobs positions are really different from one company to another
```{r}
#cleaning of the variable
reviews.complete <-
  separate(
    data = reviews.complete,
    col = employee_role,
    into = c(NA, "employee_role"),
    sep = "\\-"
  )

jobs.corpus <- corpus(x = reviews.complete,
                      text_field = c("employee_role"))

jobs.tokens <- tokens(
  jobs.corpus,
  remove_punct = TRUE,
  remove_symbols = TRUE,
  what = "word"
)

jobs.dfm <- dfm(jobs.tokens)
jobs.company <- reviews.complete$company
jobs.dfm$company <- jobs.company
jobs.dfm <- dfm_group(jobs.dfm, groups = "company")

#analysis of most frequent job positions
jobs.df<-convert(jobs.dfm,to = "data.frame")




# Representation of the job position on the biplot
tmod <- textmodel_lsa(jobs.dfm, nd = 3)
biplot(
  y = tmod$docs[, 2:3],
  x = tmod$features[, 2:3],
  col = c("grey", "red"),
  xlab = "Dim 2",
  ylab = "Dim 3"
)

```


